### ISSUE TITLE
Creating a responsive header

### ISSUE THREAD

**Issue by Aditya61101** [PrateekUp/Njack-website#1]
Add a small logo of Njack and links : Home, Events, Team, Contact and Codepeak. Header should be fixed. Add good animations. Best design will be accepted.

**Comment by ShivaRapolu01** [comment]
I would like to take this up.

**Comment by PrateekUp** [comment]
> I would like to take this up.

Go for it

**Comment by riyajha2305** [comment]
Can I work in this issue?

**Comment by aritroCoder** [comment]
I have made a header for this website. Assign it to me, and I will make the PR
![NJack_header](https://user-images.githubusercontent.com/92646038/144712870-5f80c12d-f436-4a46-8040-4b160e01a2c8.png)

**Comment by aritroCoder** [comment]
I have created a PR

https://user-images.githubusercontent.com/92646038/144735996-884f8354-fbc2-4b21-b432-6abb1d969e99.mp4

.
