### ISSUE TITLE
Fix the issues of landing page(index).

### ISSUE THREAD

**Issue by PrateekUp** [PrateekUp/Njack-website#10]
1-In mobile view, the white strokes are covering the NJACK logo(big one) which is not good and also fix the overflow(if present).
2-In Navbar, the width of njack logo should be a bit small.
3-The events tab in navbar is not working properly.

Feel Free to contact on our discord server as well as here on comments.

**Comment by chandrashekar27** [comment]
I would like to work on this.

**Comment by PrateekUp** [comment]
go on @chandrashekar27

**Comment by ShivaRapolu01** [comment]
I would like to take this issue

**Comment by adv6273** [comment]
can i solve this? @PrateekUp

**Comment by aritroCoder** [comment]
I want to work on this
