### ISSUE TITLE
Create an Events page.

### ISSUE THREAD

**Issue by PrateekUp** [PrateekUp/Njack-website#11]
Create a RESPONSIVE events page using HTML,CSS,JS. You can use libraries too. PLEASE KEEP COLOR SCHEMES AND THEMES SAME AS OUR LANDING PAGE. For the content you use some dummy content as of now. 
This is a medium level issue so please make some impressive design with animations.

**Comment by ShilpaKanjilal12** [comment]
Sir, can you assign this issue to me?

**Comment by PrateekUp** [comment]
Yes you can start working on this
