### ISSUE TITLE
Create a Team Page.

### ISSUE THREAD

**Issue by PrateekUp** [PrateekUp/Njack-website#12]
Create a RESPONSIVE Team page using HTML,CSS,JS. PLEASE KEEP COLOR SCHEMES AND THEMES MATCHING WITH OUR LANDING PAGE. For the design, it is recommended to have a look on our Codepeak Website(https://www.codepeak.tech/team) and of course a better idea is always welcome. 
The hierarchy is like this:
1- One Overall Coordinator
2- Coordinators of all Four departments
3- Subcoordinators of all four departments.

As of now it is recommended to use dummy content.
Feel free to contact us on our discord:)

**Comment by ShivaRapolu01** [comment]
Can I work on this? Please assign this to me

**Comment by PrateekUp** [comment]
Ok you can go for it

**Comment by re4lvanshsingh** [comment]
@PrateekUp bhaiya could i work on this? im iitp fresher

**Comment by ShivaRapolu01** [comment]
@PrateekUp  I have created a Team page . Please merge my pending PR so that I can raise PR for this
