### ISSUE TITLE
Adding favicon to the website

### ISSUE THREAD

**Issue by ShivaRapolu01** [PrateekUp/Njack-website#16]
Njack logo should be added to the website

**Comment by ShivaRapolu01** [comment]
I want to work on this, please assign this to me

**Comment by mikrokosmos2109** [comment]
Can only one person contribute to any issue?

**Comment by ShivaRapolu01** [comment]
@PrateekUp Please have look at this issue

**Comment by PrateekUp** [comment]
Yes you can start working on this issue. In the favicon part you have to add the small logo of njack which is 'N' only.

**Comment by ShivaRapolu01** [comment]
Yeah will do this
