### ISSUE TITLE
Make all texts in website in a uniform pattern.

### ISSUE THREAD

**Issue by PrateekUp** [PrateekUp/Njack-website#21]
In this issue you have to basically apply a uniform font pattern in all texts in the website. Remember all pages are included in this issue.
For query contact on our discord channel.

**Comment by ShivaRapolu01** [comment]
I would like to work on this

**Comment by ShivaRapolu01** [comment]
@PrateekUp Can I work on this?

**Comment by PrateekUp** [comment]
ok

**Comment by ShivaRapolu01** [comment]
What kind of font changes are to be made ?
Whole website font-family has to be changed?

**Comment by PrateekUp** [comment]
I mean make uniformity in fonts used in all three pages. for eg. similar weighted titles should have same font and content should have same point. For example I didnt like teams page font so you can do it there.

**Comment by ShivaRapolu01** [comment]
Ohk thanks will do it 👍
