### ISSUE TITLE
Make a footer

### ISSUE THREAD

**Issue by PrateekUp** [PrateekUp/Njack-website#3]
Make a responsive footer with good design.
Footer will contain social media handles of NJACK and IIT Patna.

**Comment by ShilpaKanjilal12** [comment]
I am a beginner. Can you assign this issue to me.

**Comment by PrateekUp** [comment]
> 

Yes, you can fork it and can start working on it. Do some research and add social media links of NJACK and IITP (you can get through google or our old website or from codepeak website) in footer. Make a good design and send a PR.

**Comment by riyajha2305** [comment]
Can I work on this issue?

**Comment by Ananmayd** [comment]
hello ! I am a beginner and I have some basic knowledge of HTML and CSS . So can I work on this issue ?

**Comment by Anirudh-Y** [comment]
Hello, I would like to work on this.
Can you provide a brief idea about what all links do you want.
